close #10 detail district screen
niptict-g6/cambodia_geography pull request #14
Opened 2021-07-13 17:15 UTC by darot-chen

<img width="461" alt="Screen Shot 2021-07-14 at 12 13 03 AM" src="https://user-images.githubusercontent.com/64341213/125496517-8dca063d-913f-4106-9797-21da4ad25485.png">
<img width="461" alt="Screen Shot 2021-07-14 at 12 12 56 AM" src="https://user-images.githubusercontent.com/64341213/125496535-1c6c13c8-87a6-4ab2-82c7-c234cba2e09d.png">

2021-07-14 01:54 UTC, theacheng commented
@darot-chen please use a bit more padding on top and bottom on each tile. Material only gives us guidance and styling that work best for most English fonts. This tile looks very small with Khmer font. 

![image](https://user-images.githubusercontent.com/29684683/125548254-92b6c1f6-9fd2-49b1-a6cf-668f0f781e0b.png)

2021-07-14 02:01 UTC, darot-chen commented
> @darot-chen
> 
>     * please use a bit more padding on top and bottom on each tile. Material only gives us guidance and styling that work best for most English fonts. This tile looks very small with Khmer font.
> 
>     * use the lighter background for ភូមិ
> 
>     * no border when tile is opened
> 
>     * use default centerTitle (remove it from appBar or keep it null) for page transition.

<img width="453" alt="Screen Shot 2021-07-14 at 9 00 04 AM" src="https://user-images.githubusercontent.com/64341213/125548776-72f81592-4419-4141-859c-48ed8b6f847f.png">

2021-07-14 02:06 UTC, theacheng requested changes

2021-07-14 02:06 UTC, theacheng commented on lib/screens/home/local_widget/province_card.dart
>                    : ListTile(
we should just update the title & subtitle here, so we don't have to write 2 widgets

eg. 
```dart
String title, subtitle;
if(isKrong || isKhan){title = "sth", subtitle = "sth"}
else {title = "1", subtitle = "2"}
```

2021-07-14 02:06 UTC, theacheng commented on lib/screens/district/district_screen.dart
> +            centerTitle: true,
let us use default `centerTitle`, since it help improve animation when page transition.

2021-07-15 01:16 UTC, theacheng approved these changes

2021-07-15 01:16 UTC, theacheng commented
@darot-chen  Cool

2021-07-15 01:16 UTC, merged